### ISSUE TITLE
ember-cli-foundation-sass on a new Ember 2 app with Node 4.1.0

### ISSUE THREAD

**Issue by chrisbenson** [nadavshatz/ember-cli-foundation-sass#30]
I'm trying to install ember-cli-foundation-sass on a new Ember 2 app, created using ember-cli running on Node 4.1.0.

The Ember 2 app installs fine, but when I run this command, I get the following errors:

$ **ember install ember-cli-foundation-sass**
Future versions of Ember CLI will not support v4.1.0. Please update to Node 0.12 or io.js.
version: 1.13.8
Installed packages for tooling via npm.
installing ember-cli-foundation-sass
Installing browser packages via Bower...
  cached git://github.com/zurb/bower-foundation.git#5.5.2
  cached git://github.com/jquery/jquery.git#2.1.4
  cached git://github.com/Modernizr/Modernizr.git#2.8.3
  cached git://github.com/carhartl/jquery-cookie.git#1.4.1
  cached git://github.com/mathiasbynens/jquery-placeholder.git#2.0.9
  cached git://github.com/ftlabs/fastclick.git#1.0.6
  new version for git://github.com/Modernizr/Modernizr.git#>= 2.7.2
  cached git://github.com/jquery/jquery.git#2.1.4
  resolved git://github.com/Modernizr/Modernizr.git#3.0.0
  conflict Unable to find suitable version for jquery
    1) jquery ^1.11.3
    2) jquery >=1.6
    3) jquery >=1.2
    4) jquery >= 2.1.0
    5) jquery >= 1.7.0 < 2.2.0
[?] Answer: 1
Installed browser packages via Bower.
  create app/styles/app.scss
  install packages ember-cli-sass, broccoli-clean-css
Installing packages for tooling via npm..Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-4.1/binding.node
Installing packages for tooling via npm2015-09-18 13:05:29.191 xcodebuild[10022:348545] [MT] PluginLoading: Required plug-in compatibility UUID 0420B86A-AA43-4792-9ED0-6FE0F2B16A13 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-18 13:05:29.193 xcodebuild[10022:348545] [MT] PluginLoading: Required plug-in compatibility UUID 0420B86A-AA43-4792-9ED0-6FE0F2B16A13 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmBrowser.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Installing packages for tooling via npm.  CXX(target) Release/obj.target/binding/src/binding.o
Installing packages for tooling via npm..In file included from ../src/binding.cpp:1:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../node_modules/nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~
../node_modules/nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~~~
/Users/Chris/.node-gyp/4.1.0/src/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/Chris/.node-gyp/4.1.0/src/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/Chris/.node-gyp/4.1.0/src/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/Chris/.node-gyp/4.1.0/src/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/binding.cpp:1:
../node_modules/nan/nan.h:772:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Chris/.node-gyp/4.1.0/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      
/Users/Chris/.node-gyp/4.1.0/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      
/Users/Chris/.node-gyp/4.1.0/deps/v8/include/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            
/Users/Chris/.node-gyp/4.1.0/deps/v8/include/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            
In file included from ../src/binding.cpp:1:
../node_modules/nan/nan.h:779:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~
Installing packages for tooling via npm...../src/binding.cpp:70:11: warning: 'FatalException' is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
    node::FatalException(try_catch);
          
/Users/Chris/.node-gyp/4.1.0/src/node.h:283:29: note: 'FatalException' has been explicitly marked deprecated here
                inline void FatalException(const v8::TryCatch& try_catch) {
                            ^
/Users/Chris/.node-gyp/4.1.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/binding.cpp:245:11: warning: 'FatalException' is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
    node::FatalException(try_catch);
          
/Users/Chris/.node-gyp/4.1.0/src/node.h:283:29: note: 'FatalException' has been explicitly marked deprecated here
                inline void FatalException(const v8::TryCatch& try_catch) {
                            
/Users/Chris/.node-gyp/4.1.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         
../src/binding.cpp:365:11: warning: 'FatalException' is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
    node::FatalException(try_catch);
          
/Users/Chris/.node-gyp/4.1.0/src/node.h:283:29: note: 'FatalException' has been explicitly marked deprecated here
                inline void FatalException(const v8::TryCatch& try_catch) {
                            
/Users/Chris/.node-gyp/4.1.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         
In file included from ../src/binding.cpp:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/Chris/.node-gyp/4.1.0/src/node.h:42:
/Users/Chris/.node-gyp/4.1.0/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ~~~~~~~~~~~~~~~
/Users/Chris/.node-gyp/4.1.0/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                     ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:501:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             
In file included from ../src/binding.cpp:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/Chris/.node-gyp/4.1.0/src/node.h:42:
/Users/Chris/.node-gyp/4.1.0/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Chris/.node-gyp/4.1.0/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                     ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:511:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             
In file included from ../src/binding.cpp:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/Chris/.node-gyp/4.1.0/src/node.h:42:
/Users/Chris/.node-gyp/4.1.0/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ~~~~~~~~~~~~~~~
/Users/Chris/.node-gyp/4.1.0/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                     ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1645:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             
In file included from ../src/binding.cpp:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/Chris/.node-gyp/4.1.0/src/node.h:42:
/Users/Chris/.node-gyp/4.1.0/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ~~~~~~~~~~~~~~~
/Users/Chris/.node-gyp/4.1.0/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                     ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1776:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(
           
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             
3 warnings and 10 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Chris/pet-web/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/node_modules/pangyp/lib/build.js:272:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/Chris/.nvm/versions/node/v4.1.0/bin/node" "/Users/Chris/pet-web/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/Chris/pet-web/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass
gyp ERR! node -v v4.1.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
Build failed
Installed packages for tooling via npm.
Installed addon package.
Chriss-MacBook-Pro:pet-web Chris$ ember serve
`libsass` bindings not found. Try reinstalling `node-sass`?
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/Chris/pet-web/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/Chris/pet-web/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Chris/pet-web/node_modules/ember-cli-sass/node_modules/broccoli-sass/index.js:5:12)
    at Module._compile (module.js:434:26)

**Comment by elwayman02** [comment]
@chrisbenson this is a known issue in Ember-CLI. Not related to this addon, afaik

**Comment by chrisbenson** [comment]
@elwayman02 I can install Ember without any problems using Ember CLI on Node 4.1.0, and "ember server" runs fine.  It's not until I enter the "ember install ember-cli-foundation-sass" command that things go awry.

Do you have a link to the relevant Ember CLI issue?  Thanks.

**Comment by iamsolankiamit** [comment]
Same error Here

```
Installed packages for tooling via npm.
installing ember-cli-foundation-sass
Installing browser packages via Bower...
  cached git://github.com/zurb/bower-foundation.git#5.5.2
Installed browser packages via Bower.
  identical app/styles/app.scss
  install packages ember-cli-sass, broccoli-clean-css
Installing packages for tooling via npm..Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/linux-x64-node-4.1/binding.node
Installing packages for tooling via npm.make: Entering directory '/home/fash/prototypes/propertyforest/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/build'
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cpp:1:0:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/binding.cpp:1:
/home/fash/.node-gyp/4.1.0/src/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/fash/.node-gyp/4.1.0/src/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/fash/.node-gyp/4.1.0/src/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/fash/.node-gyp/4.1.0/src/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/binding.cpp:1:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
Installing packages for tooling via npm..../src/binding.cpp: In function ‘void dispatched_async_uv_callback(uv_async_t*)’:
../src/binding.cpp:70:35: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/fash/.node-gyp/4.1.0/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(try_catch);
                                   ^
../src/binding.cpp: In function ‘void make_callback(uv_work_t*)’:
../src/binding.cpp:245:35: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/fash/.node-gyp/4.1.0/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(try_catch);
                                   ^
../src/binding.cpp: In function ‘void ImportedCallback(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/binding.cpp:365:35: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/fash/.node-gyp/4.1.0/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(try_catch);
                                   ^
binding.target.mk:128: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/fash/prototypes/propertyforest/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/fash/prototypes/propertyforest/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/node_modules/pangyp/lib/build.js:272:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-26-generic
gyp ERR! command "/home/fash/.nvm/versions/node/v4.1.0/bin/node" "/home/fash/prototypes/propertyforest/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/fash/prototypes/propertyforest/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass
gyp ERR! node -v v4.1.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
Build failed
Installed packages for tooling via npm.
Installed addon package.

```

**Comment by iamsolankiamit** [comment]
```
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/linux-x64-node-4.1/binding.node
```
Updating node-sass to 3.3.3 would help I guess

**Comment by elwayman02** [comment]
@chrisbenson https://github.com/ember-cli/ember-cli/issues/4814

**Comment by elwayman02** [comment]
Ember-CLI supports all versions of node > 0.10. Your other dependencies are not guaranteed on Node 4, however.  That's up to you to determine, but it isn't a bug of this addon.

**Comment by chrisbenson** [comment]
@elwayman02 I appreciate the link, and I agree with you completely, but that's not the issue I'm having.

Your link has to do with the message you get, which is a trivial bug, but it doesn't actually stop you from using Ember CLI on Node 4.  Like I said previously above, I'm having no problem using Ember CLI on Node.

The problem here is completely different - something in the dependency chain of this addon does not use the current version of the node-sass binary, which is required to use Sass on Node 4.  I agree it's not in the code in this addon, but it is in the code of one of its dependencies for Sass.

**Comment by elwayman02** [comment]
@chrisbenson :+1: sorry for misunderstanding the issue :)

**Comment by chrisbenson** [comment]
@elwayman02 No worries!  Thank you very much for trying to help me!

**Comment by davidgoli** [comment]
:+1: also getting this when buildling/deploying to Heroku using the ember-cli buildpack

**Comment by cresg820** [comment]
Downgrading to node 0.12 works
http://stackoverflow.com/questions/7718313/how-to-change-to-an-older-version-of-node-js?answertab=oldest#tab-top

**Comment by davidgoli** [comment]
Yes I was able to get this working by downgrading node. This plugin needs to get updated to support current versions of node, however.

**Comment by nadavshatz** [comment]
I'm using `ember-cli` v2.5 and `node` v4.4.4 with the new `v2.0` of the addon and it works fine.
Closing this for new version, please let me know if it still doesn't work.
